name: Core/Test
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests
on:
  push:
    branches:
      - dev
      - release/*
      - debug-one-off-runners
    paths-ignore:
      - 'docs/**'
      - 'help/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'docs/**'
      - 'help/**'

jobs:
  units:
    name: Units
    if: github.repository == 'opf/openproject'
    runs-on: [self-hosted,public]
    timeout-minutes: 30
    env:
      CI_CACHE_PATH: "/tmp/${{ github.sha }}/"
      CI_JOBS: 16
      CI_RETRY_COUNT: 3
      LOCAL_DEV_CHECK: 1
    steps:
    - uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: /tmp/${{ github.sha }}
        key: ${{ runner.os }}-core-tests
    - name: test
      run: |
        cp .env.example .env
        docker-compose -f docker-compose.ci.yml build ci
        docker-compose -f docker-compose.ci.yml run ci setup-tests run-units
    - name: cleanup
      if: ${{ always() }}
      run: |
        docker-compose -f docker-compose.ci.yml down --remove-orphans -t 10
        sudo chown -R $(whoami):$(id -ng) $CI_CACHE_PATH
  features:
    needs: units
    name: Features
    if: github.repository == 'opf/openproject'
    runs-on: [self-hosted,public]
    timeout-minutes: 200
    env:
      CI_JOBS: 16
      CI_CACHE_PATH: "/tmp/${{ github.sha }}/"
      LOCAL_DEV_CHECK: 1
      CI_RETRY_COUNT: 3
    steps:
    - uses: actions/checkout@v2
    - name: cache
      uses: actions/cache@v2
      with:
        path: /tmp/${{ github.sha }}
        key: ${{ runner.os }}-core-tests
    - name: test
      run: |
        cp .env.example .env
        docker-compose -f docker-compose.ci.yml build ci
        docker-compose -f docker-compose.ci.yml run ci setup-tests run-features
    - name: cleanup
      if: ${{ always() }}
      run: |
        docker-compose -f docker-compose.ci.yml down --remove-orphans -t 10
        sudo chown -R $(whoami):$(id -ng) $CI_CACHE_PATH
